name: Build and deploy CV

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.tex"
      - "**.cls"
      - "**.sty"
      - "**.bib"

jobs:
  issue_voucher:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out this voucher
        uses: actions/checkout@v3

      - name: Compiling voucher
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Change pdf filename
        run: mv main.pdf cv.pdf

      - name: push to website
        uses: GuillaumeFalourd/git-commit-push@v1
        with:
          files: cv.pdf
          remote_repository: https://github.com/natestemen/natestemen.xyz
          force: true
          email: octocat@github.com
          name: octocat
