name: Build and deploy CV

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  issue_voucher:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out this voucher
        uses: actions/checkout@v4

      - name: Compiling voucher
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Renaming voucher
        run: mv main.pdf cv.pdf

      - name: Publishing voucher release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest CV
          files: cv.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delivering voucher to website
        run: gh workflow run deploy.yml --repo natestemen/nates.place
        env:
          GH_TOKEN: ${{ secrets.NATES_PLACE_DISPATCH_TOKEN }}
