name: Build and deploy CV

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.tex"
      - "**.cls"
      - "**.sty"
      - "**.bib"

jobs:
  issue_voucher:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out this voucher
        uses: actions/checkout@v3

      - name: Compiling voucher
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Setup push to website
        run: |
          mkdir output
          mv main.pdf output/cv.pdf

      - name: push to website repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "output"
          destination-github-username: "natestemen"
          destination-repository-name: "natestemen.xyz"
          user-name: octocat
          user-email: octocat@github.com
