name: Build and deploy CV

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.tex"
      - "**.cls"
      - "**.sty"
      - "**.bib"

jobs:
  issue_voucher:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out this voucher
        uses: actions/checkout@v3

      - name: Compiling voucher
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Setup push to website
        run: |
          mkdir output
          mv main.pdf cv.pdf

      - name: push to website repo
        uses: actions/checkout@v3
        with:
          ssh_key: ${{ secrets.SSH_DEPLOY_KEY }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add cv.pdf
          git commit -m "CV update"
          git push
