name: Build and deploy CV

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.tex"
      - "**.cls"
      - "**.sty"
      - "**.bib"

jobs:
  issue_voucher:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out this voucher
        uses: actions/checkout@v3

      - name: Compiling voucher
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - uses: actions/upload-artifact@v3
        with:
          name: cv-pdf
          path: main.pdf

      - name: checkout website repo
        uses: actions/checkout@v3
        with:
          repository: natestemen/natestemen.xyz
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - uses: actions/download-artifact@v3
        with:
          name: cv-pdf

      - name: push to website
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.pdf
          git commit -m "CV update"
          git push
