name: Build and deploy CV

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  issue_voucher:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out this voucher
        uses: actions/checkout@v3

      - name: Compiling voucher
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Uploading voucher
        uses: actions/upload-artifact@v3
        with:
          name: cv-pdf
          path: main.pdf

      - name: Checking out website repo
        uses: actions/checkout@v3
        with:
          repository: natestemen/natestemen.xyz
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Downloading voucher
        uses: actions/download-artifact@v4.1.7
        with:
          name: cv-pdf

      - name: Pushing voucher to website
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          mv main.pdf cv.pdf
          git add cv.pdf
          git commit -m "CV update"
          git push
