name: Remind me to update voucher

on:
  schedule:
    - cron: "51 7 8 */3 *"

permissions:
  issues: write

jobs:
  remind:
    name: Remind me to update my voucher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/remind.md
