name: Keep repo active

on:
  schedule:
    - cron: "0 0 1 */1 *"
  workflow_dispatch:

jobs:
  comment_on_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment 21 --body "🌞 stayin alive 🌞"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: natestemen/cultvoucher
